Set sess_save_path, because error occured on travis-ci
Exception: Session: Configured save path '' is not a directory, doesn't exist or cannot be created.